- name: Install packages
  apt:
    pkg:
    - vim
    - git
    - tree
    - htop
    - emacs
    - net-tools
    - sudo
    - make
    - unzip
    - python3
    - python3-pip

- name: Apt-get update
  apt:
    update_cache: yes
