- name: Install php
  apt:
    pkg:
    - php7.3
    - php7.3-cli
    - php7.3-fpm
    - php7.3-json
    - php7.3-pdo
    - php7.3-mysql
    - php7.3-zip
    - php7.3-gd
    - php7.3-mbstring
    - php7.3-curl
    - php7.3-xml
    - php-pear
    - php7.3-bcmath
    - php7.3-intl

- name: Set php7.3 timezone
  become: true
  lineinfile:
    dest: /etc/php/7.3/cli/php.ini
    regexp: "date.timezone ="
    line: "date.timezone = Europe/Paris"

